[package]
name = "enum_parse"
version = "0.1.0"
edition = "2021"
authors = ["Darek Stojaczyk <darek@stojaczyk.pl>"]
repository = "https://github.com/darsto/enum_parse"
readme = "README.md"
keywords = ["enum", "macro", "attribute", "parser", "serialization"]
categories = ["parsing", "rust-patterns"]
license = "MIT"
description = """
Procedural macro generating boilerplate code for parsing enum variants
"""

[lib]
proc-macro = true
doctest = false

[dependencies]
proc-macro2 = "^1.0"
quote = "^1.0"
syn = { version = "^2.0" }

[dev-dependencies]
zerocopy = { version = "^0.7", features = ["derive"] }
